export const POSTS = {
    GET_POSTS_REQUEST:"GET_POSTS_REQUEST",
    GET_POSTS_SUCCESS:"GET_POSTS_SUCCESS",
    GET_POSTS_FAILURE:"GET_POSTS_FAILURE",


    POSTS_DELETE_REQUEST:"POSTS_DELETE_REQUEST",
    POSTS_DELETE_SUCCESS:"POSTS_DELETE_SUCCESS",
    POSTS_DELETE_FAILURE:"POSTS_DELETE_FAILURE",


    POSTS_CREATE_REQUEST:"POSTS_CREATE_REQUEST",
    POSTS_CREATE_SUCCESS:"POSTS_CREATE_SUCCESS",
    POSTS_CREATE_FAILURE:"POSTS_CREATE_FAILURE",

    POSTS_EDIT_REQUEST:"POSTS_EDIT_REQUEST",
    POSTS_EDIT_SUCCESS:"POSTS_EDIT_SUCCESS",
    POSTS_EDIT_FAILURE:"POSTS_EDIT_FAILURE",
}