export const AUTH = {
    CREATE_USERS_ACCOUNT_REQUEST: "CREATE_USERS_ACCOUNT_REQUEST",
    CREATE_USERS_ACCOUNT_SUCCESS: "CREATE_USERS_ACCOUNT_SUCCESS",
    CREATE_USERS_ACCOUNT_FAILURE: "CREATE_USERS_ACCOUNT_FAILURE",

    LOGIN_REQUEST: "LOGIN_REQUEST",
    LOGIN_SUCCESS: "LOGIN_SUCCESS",
    LOGIN_FAILURE: "LOGIN_FAILURE",
}
