export const AUTH = {
    CREATE_USERS_ACCOUNT_REQUEST: "CREATE_USERS_ACCOUNT_REQUEST",
    CREATE_USERS_ACCOUNT_SUCCESS: "CREATE_USERS_ACCOUNT_SUCCESS",
    CREATE_USERS_ACCOUNT_FAILURE: "CREATE_USERS_ACCOUNT_FAILURE",
}